### PR TITLE
feat: treat flights from ireland as domestic for stand purposes

### PR DESCRIPTION
**Pull request by AndyTWF**

### CODE REVIEW

**Comment by cpawley** [comment]
Arrivals from EIxx, EGJJ/EGJB/EGJA (and perhaps others) are required to bypass UK border but pass through customs. So they go via a different route than a true domestic. (which avoids both the border and the customs check)

So at Heathrow, EIxx/EGJJ arrivals are on stand 523/225/226 but domestics are 501-507 or so. 

Not sure if this change would affect this, maybe go for a seperate designation isCTA (common transit area) (from EIxx, EGJJ/EGJB/EGJA) and then handle those different to all other EGxx's...

For an EGNS, that's again something to check - I believe that's handled as a domestic :)

**Comment by AndyTWF** [comment]
> Arrivals from EIxx, EGJJ/EGJB/EGJA (and perhaps others) are required to bypass UK border but pass through customs. So they go via a different route than a true domestic. (which avoids both the border and the customs check)
> 
> So at Heathrow, EIxx/EGJJ arrivals are on stand 523/225/226 but domestics are 501-507 or so.
> 
> Not sure if this change would affect this, maybe go for a seperate designation isCTA (common transit area) (from EIxx, EGJJ/EGJB/EGJA) and then handle those different to all other EGxx's...
> 
> For an EGNS, that's again something to check - I believe that's handled as a domestic :)

So this is just for the fallback allocators - mostly used at EGAA. In the case of LL T5 the airline preferences take precedence :)

**Comment by cpawley** [comment]
great <3

**Review by AxonC — APPROVED** [review]

**Pull request merged**
